export default [
    { id: 1, name: "Воробьёв Ю.С.", customer: "НИИ Склифосовского", registrationDate: new Date(2023, 8, 16), color: "#A6BFDF" },
    { id: 2, name: "Миронов Н.Р.", customer: null, registrationDate: new Date(2024, 3, 7), color: "#B6A3F2" },
    { id: 3, name: "Щербаков Р.Ю.", customer: "МОНИКИ", registrationDate: new Date(2024, 11, 26), color: "#BDC9FC" },
    { id: 4, name: "Виноградов Э.Ф.", customer: null, registrationDate: new Date(2024, 9, 25), color: null },
    { id: 5, name: "Виноградов Р.Д.", customer: "НИИ Склифосовского", registrationDate: new Date(2025, 8, 12), color: null },
    { id: 6, name: "Лебедев В.Ц.", customer: null, registrationDate: new Date(2024, 2, 2), color: "#EBC4A9" },
    { id: 7, name: "Смирнов П.И.", customer: null, registrationDate: new Date(2022, 8, 7), color: "#B4AFD7" },
    { id: 8, name: "Большаков Ж.У.", customer: null, registrationDate: new Date(2024, 6, 14), color: "#C6FDD6" },
    { id: 9, name: "Филиппов Е.А.", customer: null, registrationDate: new Date(2022, 2, 24), color: "#D1E4D0" },
    { id: 10, name: "Щербаков Щ.И.", customer: "ЦРБ Подольск", registrationDate: new Date(2020, 5, 12), color: null },
    { id: 11, name: "Андреев К.З.", customer: "НИИ Склифосовского", registrationDate: new Date(2024, 0, 27), color: "#E2D1FB" },
    { id: 12, name: "Голубев Е.П.", customer: "ЦРБ Подольск", registrationDate: new Date(2021, 0, 26), color: "#E8A7E3" },
    { id: 13, name: "Тихонов Б.Р.", customer: "НИИ Склифосовского", registrationDate: new Date(2023, 10, 27), color: null },
    { id: 14, name: "Голубев Д.Ф.", customer: "ГКБ №1", registrationDate: new Date(2023, 0, 4), color: null },
    { id: 15, name: "Козлов Э.К.", customer: "Поликлиника №3", registrationDate: new Date(2022, 4, 22), color: "#C8C6D9" },
    { id: 16, name: "Григорьев Ш.Л.", customer: "НИИ Склифосовского", registrationDate: new Date(2019, 4, 8), color: "#A2C8CF" },
    { id: 17, name: "Соколов Ш.С.", customer: null, registrationDate: new Date(2020, 5, 21), color: null },
    { id: 18, name: "Сидоров Ш.Б.", customer: null, registrationDate: new Date(2021, 9, 21), color: "#BCFEE9" },
    { id: 19, name: "Шестаков Ф.Ц.", customer: "МОНИКИ", registrationDate: new Date(2020, 1, 17), color: null },
    { id: 20, name: "Тихонов Х.Ц.", customer: "НИИ Склифосовского", registrationDate: new Date(2023, 8, 30), color: "#C0C7FA" },
    { id: 21, name: "Денисов В.Ш.", customer: null, registrationDate: new Date(2019, 3, 25), color: null },
    { id: 22, name: "Суханов Э.Н.", customer: null, registrationDate: new Date(2022, 10, 23), color: "#C3EEF9" },
    { id: 23, name: "Сидоров Х.П.", customer: "Поликлиника №3", registrationDate: new Date(2024, 0, 27), color: "#BDF8A0" },
    { id: 24, name: "Широков В.Н.", customer: "НИИ Склифосовского", registrationDate: new Date(2022, 10, 5), color: null },
    { id: 25, name: "Казаков Щ.Т.", customer: "ГКБ №1", registrationDate: new Date(2023, 10, 27), color: "#BFB1AB" },
    { id: 26, name: "Суханов Г.О.", customer: "ГКБ №1", registrationDate: new Date(2024, 3, 7), color: "#A6C6E0" },
    { id: 27, name: "Широков Щ.Г.", customer: null, registrationDate: new Date(2020, 6, 2), color: "#AAD1AF" },
    { id: 28, name: "Тихонов О.Г.", customer: "ЦРБ Подольск", registrationDate: new Date(2021, 8, 15), color: null },
    { id: 29, name: "Мельников Ю.М.", customer: "НИИ Склифосовского", registrationDate: new Date(2022, 10, 5), color: "#E6EFA4" },
    { id: 30, name: "Фомин С.У.", customer: null, registrationDate: new Date(2019, 5, 17), color: "#A8E3C8" },
    { id: 31, name: "Зуев Т.Д.", customer: "ГКБ №1", registrationDate: new Date(2024, 6, 31), color: null },
    { id: 32, name: "Степанов Ж.Г.", customer: "Поликлиника №3", registrationDate: new Date(2024, 7, 10), color: "#C5BDF5" },
    { id: 33, name: "Фомин Ч.А.", customer: "ГКБ №1", registrationDate: new Date(2023, 7, 31), color: null },
    { id: 34, name: "Александров К.Н.", customer: null, registrationDate: new Date(2025, 10, 25), color: "#EEB7B4" },
    { id: 35, name: "Голубев Н.У.", customer: "НИИ Склифосовского", registrationDate: new Date(2019, 2, 15), color: "#EFD7FF" },
    { id: 36, name: "Зуев Л.Ш.", customer: "НИИ Склифосовского", registrationDate: new Date(2021, 5, 29), color: "#CECDA8" },
    { id: 37, name: "Петров Ш.Ш.", customer: "Поликлиника №3", registrationDate: new Date(2023, 8, 1), color: "#CECBF9" },
    { id: 38, name: "Виноградов Я.Ч.", customer: "МОНИКИ", registrationDate: new Date(2018, 1, 19), color: "#BFAFF1" },
    { id: 39, name: "Щербаков Ж.Н.", customer: "НИИ Склифосовского", registrationDate: new Date(2018, 9, 14), color: null },
    { id: 40, name: "Богданов Я.З.", customer: "НИИ Склифосовского", registrationDate: new Date(2021, 7, 3), color: "#ADCDED" },
    { id: 41, name: "Морозов М.Ш.", customer: null, registrationDate: new Date(2023, 3, 23), color: "#CFCFCB" },
    { id: 42, name: "Александров Л.В.", customer: null, registrationDate: new Date(2019, 6, 25), color: null },
    { id: 43, name: "Блинов Щ.Э.", customer: "ГКБ №1", registrationDate: new Date(2019, 10, 2), color: "#FEE7D1" },
    { id: 44, name: "Филиппов А.С.", customer: null, registrationDate: new Date(2023, 8, 20), color: null },
    { id: 45, name: "Громов Ч.К.", customer: "ГКБ №1", registrationDate: new Date(2024, 11, 22), color: null },
    { id: 46, name: "Ершов И.Б.", customer: "НИИ Склифосовского", registrationDate: new Date(2023, 9, 30), color: "#C7E8BB" },
    { id: 47, name: "Мельников Р.С.", customer: "ГКБ №1", registrationDate: new Date(2018, 7, 14), color: "#E7C4AC" },
    { id: 48, name: "Андреев Ч.Ю.", customer: null, registrationDate: new Date(2023, 2, 20), color: "#D9DDE2" },
    { id: 49, name: "Щербаков Г.Р.", customer: null, registrationDate: new Date(2021, 1, 5), color: "#C2EAE3" },
    { id: 50, name: "Миронов Ц.З.", customer: "МОНИКИ", registrationDate: new Date(2020, 6, 22), color: "#A0BCEC" },
    { id: 51, name: "Степанов М.Э.", customer: "Поликлиника №3", registrationDate: new Date(2024, 3, 7), color: "#CFF5AB" },
    { id: 52, name: "Воробьёв Б.Э.", customer: "ГКБ №1", registrationDate: new Date(2022, 1, 15), color: null },
    { id: 53, name: "Шестаков М.В.", customer: "ГКБ №1", registrationDate: new Date(2020, 2, 27), color: "#DDFDD4" },
    { id: 54, name: "Фомин Р.Ю.", customer: null, registrationDate: new Date(2022, 6, 14), color: "#F0D2B3" },
    { id: 55, name: "Иванов К.П.", customer: null, registrationDate: new Date(2024, 0, 19), color: null },
    { id: 56, name: "Александров Е.О.", customer: null, registrationDate: new Date(2021, 9, 27), color: "#FDC6AC" },
    { id: 57, name: "Соколов М.К.", customer: null, registrationDate: new Date(2025, 5, 10), color: null },
    { id: 58, name: "Михайлов Р.Х.", customer: "ГКБ №1", registrationDate: new Date(2025, 5, 20), color: null },
    { id: 59, name: "Блинов Б.Ю.", customer: "ГКБ №1", registrationDate: new Date(2024, 9, 7), color: null },
    { id: 60, name: "Козлов Ю.Р.", customer: null, registrationDate: new Date(2024, 1, 3), color: "#B3BDCD" },
    { id: 61, name: "Лазарев Ф.Н.", customer: null, registrationDate: new Date(2022, 8, 10), color: "#E3FACD" },
    { id: 62, name: "Филиппов С.Ф.", customer: null, registrationDate: new Date(2021, 6, 30), color: null },
    { id: 63, name: "Смирнов Ж.Ш.", customer: "МОНИКИ", registrationDate: new Date(2023, 10, 21), color: null },
    { id: 64, name: "Лазарев З.С.", customer: "Поликлиника №3", registrationDate: new Date(2019, 3, 25), color: "#DBFDE7" },
    { id: 65, name: "Козлов С.Т.", customer: "НИИ Склифосовского", registrationDate: new Date(2021, 1, 23), color: "#C8E5A0" },
];
