export default [
    { id: 1, name: "Воробьёв Ю.С.", customer: "НИИ Склифосовского", registrationDate: new Date(2023, 8, 16), color: "#A6BFDF" },
    { id: 2, name: "Миронов Н.Р.", customer: null, registrationDate: new Date(2024, 3, 7), color: "#B6A3F2" },
    { id: 3, name: "Щербаков Р.Ю.", customer: "МОНИКИ", registrationDate: new Date(2024, 11, 26), color: "#BDC9FC" },
    { id: 4, name: "Виноградов Э.Ф.", customer: null, registrationDate: new Date(2024, 9, 25), color: null },
    { id: 5, name: "Виноградов Р.Д.", customer: "НИИ Склифосовского", registrationDate: new Date(2025, 8, 12), color: null },
    { id: 6, name: "Лебедев В.Ц.", customer: null, registrationDate: new Date(2024, 2, 2), color: "#EBC4A9" },
    { id: 7, name: "Смирнов П.И.", customer: null, registrationDate: new Date(2022, 8, 7), color: "#B4AFD7" },
    { id: 8, name: "Большаков Ж.У.", customer: null, registrationDate: new Date(2024, 6, 14), color: "#C6FDD6" },
    { id: 9, name: "Филиппов Е.А.", customer: null, registrationDate: new Date(2022, 2, 24), color: "#D1E4D0" },
    { id: 10, name: "Щербаков Щ.И.", customer: "ЦРБ Подольск", registrationDate: new Date(2020, 5, 12), color: null },
    { id: 11, name: "Андреев К.З.", customer: "НИИ Склифосовского", registrationDate: new Date(2024, 0, 27), color: "#E2D1FB" },
    { id: 12, name: "Голубев Е.П.", customer: "ЦРБ Подольск", registrationDate: new Date(2021, 0, 26), color: "#E8A7E3" },
    { id: 13, name: "Тихонов Б.Р.", customer: "НИИ Склифосовского", registrationDate: new Date(2023, 10, 27), color: null },
    { id: 14, name: "Голубев Д.Ф.", customer: "ГКБ №1", registrationDate: new Date(2023, 0, 4), color: null },
    { id: 15, name: "Козлов Э.К.", customer: "Поликлиника №3", registrationDate: new Date(2022, 4, 22), color: "#C8C6D9" },
    { id: 16, name: "Григорьев Ш.Л.", customer: "НИИ Склифосовского", registrationDate: new Date(2019, 4, 8), color: "#A2C8CF" },
    { id: 17, name: "Соколов Ш.С.", customer: null, registrationDate: new Date(2020, 5, 21), color: null },
    { id: 18, name: "Сидоров Ш.Б.", customer: null, registrationDate: new Date(2021, 9, 21), color: "#BCFEE9" },
    { id: 19, name: "Шестаков Ф.Ц.", customer: "МОНИКИ", registrationDate: new Date(2020, 1, 17), color: null },
    { id: 20, name: "Тихонов Х.Ц.", customer: "НИИ Склифосовского", registrationDate: new Date(2023, 8, 30), color: "#C0C7FA" },
    { id: 21, name: "Денисов В.Ш.", customer: null, registrationDate: new Date(2019, 3, 25), color: null },
    { id: 22, name: "Суханов Э.Н.", customer: null, registrationDate: new Date(2022, 10, 23), color: "#C3EEF9" },
    { id: 23, name: "Сидоров Х.П.", customer: "Поликлиника №3", registrationDate: new Date(2024, 0, 27), color: "#BDF8A0" },
    { id: 24, name: "Широков В.Н.", customer: "НИИ Склифосовского", registrationDate: new Date(2022, 10, 5), color: null },
    { id: 25, name: "Казаков Щ.Т.", customer: "ГКБ №1", registrationDate: new Date(2023, 10, 27), color: "#BFB1AB" },
    { id: 26, name: "Суханов Г.О.", customer: "ГКБ №1", registrationDate: new Date(2024, 3, 7), color: "#A6C6E0" },
    { id: 27, name: "Широков Щ.Г.", customer: null, registrationDate: new Date(2020, 6, 2), color: "#AAD1AF" },
    { id: 28, name: "Тихонов О.Г.", customer: "ЦРБ Подольск", registrationDate: new Date(2021, 8, 15), color: null },
    { id: 29, name: "Мельников Ю.М.", customer: "НИИ Склифосовского", registrationDate: new Date(2022, 10, 5), color: "#E6EFA4" },
    { id: 30, name: "Фомин С.У.", customer: null, registrationDate: new Date(2019, 5, 17), color: "#A8E3C8" },
    { id: 31, name: "Зуев Т.Д.", customer: "ГКБ №1", registrationDate: new Date(2024, 6, 31), color: null },
    { id: 32, name: "Степанов Ж.Г.", customer: "Поликлиника №3", registrationDate: new Date(2024, 7, 10), color: "#C5BDF5" },
    { id: 33, name: "Фомин Ч.А.", customer: "ГКБ №1", registrationDate: new Date(2023, 7, 31), color: null },
    { id: 34, name: "Александров К.Н.", customer: null, registrationDate: new Date(2025, 10, 25), color: "#EEB7B4" },
    { id: 35, name: "Голубев Н.У.", customer: "НИИ Склифосовского", registrationDate: new Date(2019, 2, 15), color: "#EFD7FF" },
    { id: 36, name: "Зуев Л.Ш.", customer: "НИИ Склифосовского", registrationDate: new Date(2021, 5, 29), color: "#CECDA8" },
    { id: 37, name: "Петров Ш.Ш.", customer: "Поликлиника №3", registrationDate: new Date(2023, 8, 1), color: "#CECBF9" },
    { id: 38, name: "Виноградов Я.Ч.", customer: "МОНИКИ", registrationDate: new Date(2018, 1, 19), color: "#BFAFF1" },
    { id: 39, name: "Щербаков Ж.Н.", customer: "НИИ Склифосовского", registrationDate: new Date(2018, 9, 14), color: null },
    { id: 40, name: "Богданов Я.З.", customer: "НИИ Склифосовского", registrationDate: new Date(2021, 7, 3), color: "#ADCDED" },
    { id: 41, name: "Морозов М.Ш.", customer: null, registrationDate: new Date(2023, 3, 23), color: "#CFCFCB" },
    { id: 42, name: "Александров Л.В.", customer: null, registrationDate: new Date(2019, 6, 25), color: null },
    { id: 43, name: "Блинов Щ.Э.", customer: "ГКБ №1", registrationDate: new Date(2019, 10, 2), color: "#FEE7D1" },
    { id: 44, name: "Филиппов А.С.", customer: null, registrationDate: new Date(2023, 8, 20), color: null },
    { id: 45, name: "Громов Ч.К.", customer: "ГКБ №1", registrationDate: new Date(2024, 11, 22), color: null },
    { id: 46, name: "Ершов И.Б.", customer: "НИИ Склифосовского", registrationDate: new Date(2023, 9, 30), color: "#C7E8BB" },
    { id: 47, name: "Мельников Р.С.", customer: "ГКБ №1", registrationDate: new Date(2018, 7, 14), color: "#E7C4AC" },
    { id: 48, name: "Андреев Ч.Ю.", customer: null, registrationDate: new Date(2023, 2, 20), color: "#D9DDE2" },
    { id: 49, name: "Щербаков Г.Р.", customer: null, registrationDate: new Date(2021, 1, 5), color: "#C2EAE3" },
    { id: 50, name: "Миронов Ц.З.", customer: "МОНИКИ", registrationDate: new Date(2020, 6, 22), color: "#A0BCEC" },
    { id: 51, name: "Степанов М.Э.", customer: "Поликлиника №3", registrationDate: new Date(2024, 3, 7), color: "#CFF5AB" },
    { id: 52, name: "Воробьёв Б.Э.", customer: "ГКБ №1", registrationDate: new Date(2022, 1, 15), color: null },
    { id: 53, name: "Шестаков М.В.", customer: "ГКБ №1", registrationDate: new Date(2020, 2, 27), color: "#DDFDD4" },
    { id: 54, name: "Фомин Р.Ю.", customer: null, registrationDate: new Date(2022, 6, 14), color: "#F0D2B3" },
    { id: 55, name: "Иванов К.П.", customer: null, registrationDate: new Date(2024, 0, 19), color: null },
    { id: 56, name: "Александров Е.О.", customer: null, registrationDate: new Date(2021, 9, 27), color: "#FDC6AC" },
    { id: 57, name: "Соколов М.К.", customer: null, registrationDate: new Date(2025, 5, 10), color: null },
    { id: 58, name: "Михайлов Р.Х.", customer: "ГКБ №1", registrationDate: new Date(2025, 5, 20), color: null },
    { id: 59, name: "Блинов Б.Ю.", customer: "ГКБ №1", registrationDate: new Date(2024, 9, 7), color: null },
    { id: 60, name: "Козлов Ю.Р.", customer: null, registrationDate: new Date(2024, 1, 3), color: "#B3BDCD" },
    { id: 61, name: "Лазарев Ф.Н.", customer: null, registrationDate: new Date(2022, 8, 10), color: "#E3FACD" },
    { id: 62, name: "Филиппов С.Ф.", customer: null, registrationDate: new Date(2021, 6, 30), color: null },
    { id: 63, name: "Смирнов Ж.Ш.", customer: "МОНИКИ", registrationDate: new Date(2023, 10, 21), color: null },
    { id: 64, name: "Лазарев З.С.", customer: "Поликлиника №3", registrationDate: new Date(2019, 3, 25), color: "#DBFDE7" },
    { id: 65, name: "Козлов С.Т.", customer: "НИИ Склифосовского", registrationDate: new Date(2021, 1, 23), color: "#C8E5A0" },
    { id: 66, name: "Колесников Б.З.", customer: "ГКБ №1", registrationDate: new Date(2019, 9, 5), color: null },
    { id: 67, name: "Казаков Щ.З.", customer: "МОНИКИ", registrationDate: new Date(2018, 9, 4), color: "#A6D3B9" },
    { id: 68, name: "Петров О.К.", customer: "НИИ Склифосовского", registrationDate: new Date(2025, 0, 5), color: "#E2B3F7" },
    { id: 69, name: "Медведев Э.С.", customer: "МОНИКИ", registrationDate: new Date(2025, 10, 3), color: "#EED1B2" },
    { id: 70, name: "Медведев Э.Ж.", customer: "ГКБ №1", registrationDate: new Date(2023, 6, 8), color: "#BEEBB9" },
    { id: 71, name: "Михайлов А.Т.", customer: "ГКБ №1", registrationDate: new Date(2025, 4, 29), color: "#E4A6D9" },
    { id: 72, name: "Филиппов Ц.О.", customer: null, registrationDate: new Date(2024, 10, 6), color: null },
    { id: 73, name: "Волков М.Ц.", customer: "ЦРБ Подольск", registrationDate: new Date(2020, 11, 14), color: null },
    { id: 74, name: "Михайлов Ж.Я.", customer: "ГКБ №1", registrationDate: new Date(2025, 5, 2), color: null },
    { id: 75, name: "Сидоров П.Е.", customer: null, registrationDate: new Date(2018, 10, 25), color: "#D9E4F5" },
    { id: 76, name: "Марков П.О.", customer: "ЦРБ Подольск", registrationDate: new Date(2025, 1, 27), color: "#DAA3F5" },
    { id: 77, name: "Иванов П.Л.", customer: "НИИ Склифосовского", registrationDate: new Date(2020, 9, 18), color: null },
    { id: 78, name: "Григорьев З.Г.", customer: "ГКБ №1", registrationDate: new Date(2024, 10, 6), color: "#B9EFC7" },
    { id: 79, name: "Семёнов О.Ч.", customer: "Поликлиника №3", registrationDate: new Date(2023, 6, 19), color: "#E0EFED" },
    { id: 80, name: "Большаков К.А.", customer: "ГКБ №1", registrationDate: new Date(2021, 11, 30), color: null },
    { id: 81, name: "Васильев Ш.Г.", customer: null, registrationDate: new Date(2025, 0, 7), color: null },
    { id: 82, name: "Иванов И.Г.", customer: "ГКБ №1", registrationDate: new Date(2025, 3, 29), color: null },
    { id: 83, name: "Александров Х.Е.", customer: "МОНИКИ", registrationDate: new Date(2024, 2, 29), color: null },
    { id: 84, name: "Андреев Ф.Б.", customer: null, registrationDate: new Date(2023, 8, 18), color: null },
    { id: 85, name: "Коновалов Ш.Ю.", customer: null, registrationDate: new Date(2021, 1, 8), color: null },
    { id: 86, name: "Попов Е.А.", customer: null, registrationDate: new Date(2021, 4, 18), color: null },
    { id: 87, name: "Иванов Д.Ч.", customer: "ГКБ №1", registrationDate: new Date(2018, 2, 19), color: null },
    { id: 88, name: "Широков П.В.", customer: null, registrationDate: new Date(2024, 1, 28), color: null },
    { id: 89, name: "Сидоров Т.У.", customer: "ЦРБ Подольск", registrationDate: new Date(2024, 2, 4), color: "#EDC8A7" },
    { id: 90, name: "Суханов Б.Ц.", customer: "МОНИКИ", registrationDate: new Date(2020, 11, 2), color: "#F7F5DF" },
    { id: 91, name: "Виноградов Р.Л.", customer: null, registrationDate: new Date(2024, 6, 15), color: "#C0ECA3" },
    { id: 92, name: "Зуев Д.Е.", customer: "Поликлиника №3", registrationDate: new Date(2020, 7, 5), color: null },
    { id: 93, name: "Лазарев Д.Э.", customer: "МОНИКИ", registrationDate: new Date(2025, 7, 30), color: null },
    { id: 94, name: "Соколов Л.Ц.", customer: "ГКБ №1", registrationDate: new Date(2023, 2, 13), color: null },
    { id: 95, name: "Коновалов Х.Я.", customer: "ГКБ №1", registrationDate: new Date(2019, 1, 9), color: "#FDD9B4" },
    { id: 96, name: "Блинов М.У.", customer: "Поликлиника №3", registrationDate: new Date(2024, 5, 3), color: "#B4DFC5" },
    { id: 97, name: "Большаков Ж.Б.", customer: "НИИ Склифосовского", registrationDate: new Date(2020, 11, 6), color: "#DAB7FC" },
    { id: 98, name: "Волков Л.Щ.", customer: "ГКБ №1", registrationDate: new Date(2022, 5, 23), color: null },
    { id: 99, name: "Денисов Д.Х.", customer: "НИИ Склифосовского", registrationDate: new Date(2020, 8, 12), color: null },
    { id: 100, name: "Воробьёв Б.Д.", customer: "НИИ Склифосовского", registrationDate: new Date(2018, 3, 18), color: null },
    { id: 101, name: "Щербаков Э.Ж.", customer: null, registrationDate: new Date(2023, 10, 11), color: null },
    { id: 102, name: "Ефимов О.Р.", customer: null, registrationDate: new Date(2018, 2, 12), color: null },
    { id: 103, name: "Филиппов З.К.", customer: "Поликлиника №3", registrationDate: new Date(2020, 6, 28), color: null },
    { id: 104, name: "Михайлов М.Ч.", customer: "МОНИКИ", registrationDate: new Date(2018, 1, 22), color: null },
    { id: 105, name: "Андреев Ф.И.", customer: null, registrationDate: new Date(2024, 6, 16), color: "#D7DBA4" },
    { id: 106, name: "Лазарев З.Е.", customer: "ГКБ №1", registrationDate: new Date(2020, 3, 15), color: "#F7F7D7" },
    { id: 107, name: "Зуев Щ.Ф.", customer: "НИИ Склифосовского", registrationDate: new Date(2021, 1, 1), color: "#BFE6F1" },
    { id: 108, name: "Ершов Е.Ц.", customer: null, registrationDate: new Date(2025, 3, 21), color: null },
    { id: 109, name: "Виноградов Д.Э.", customer: "ГКБ №1", registrationDate: new Date(2021, 4, 31), color: "#DCFBB8" },
    { id: 110, name: "Денисов У.А.", customer: null, registrationDate: new Date(2024, 9, 7), color: null },
    { id: 111, name: "Андреев О.И.", customer: null, registrationDate: new Date(2019, 9, 1), color: "#AECAFC" },
    { id: 112, name: "Смирнов Л.Ж.", customer: null, registrationDate: new Date(2024, 8, 2), color: "#B9BFEF" },
    { id: 113, name: "Павлов Н.Д.", customer: null, registrationDate: new Date(2025, 5, 22), color: "#F6F6A6" },
    { id: 114, name: "Воробьёв Н.Ч.", customer: "ГКБ №1", registrationDate: new Date(2021, 8, 20), color: null },
    { id: 115, name: "Лебедев И.Е.", customer: null, registrationDate: new Date(2021, 7, 22), color: "#D6BFB7" },
    { id: 116, name: "Ершов Н.Х.", customer: "НИИ Склифосовского", registrationDate: new Date(2023, 4, 30), color: "#E7FBDA" },
    { id: 117, name: "Алексеев Э.Н.", customer: "ГКБ №1", registrationDate: new Date(2025, 1, 21), color: "#F1D9A4" },
    { id: 118, name: "Петров У.О.", customer: "ГКБ №1", registrationDate: new Date(2024, 10, 28), color: "#A2CACD" },
    { id: 119, name: "Петров Е.Р.", customer: "МОНИКИ", registrationDate: new Date(2022, 1, 11), color: "#E1ECCD" },
    { id: 120, name: "Сидоров Ю.Т.", customer: "Поликлиника №3", registrationDate: new Date(2018, 2, 17), color: "#DBBCD0" },
    { id: 121, name: "Богданов Э.В.", customer: "Поликлиника №3", registrationDate: new Date(2019, 4, 11), color: null },
    { id: 122, name: "Мельников Щ.З.", customer: "МОНИКИ", registrationDate: new Date(2020, 11, 2), color: "#CBBBE5" },
    { id: 123, name: "Зуев У.В.", customer: "МОНИКИ", registrationDate: new Date(2018, 10, 5), color: "#CAB0EF" },
    { id: 124, name: "Зуев М.Т.", customer: "ЦРБ Подольск", registrationDate: new Date(2022, 9, 28), color: "#DEC2E4" },
    { id: 125, name: "Коновалов Я.Е.", customer: "ГКБ №1", registrationDate: new Date(2022, 7, 4), color: null },
    { id: 126, name: "Зуев Л.Р.", customer: null, registrationDate: new Date(2023, 4, 14), color: null },
    { id: 127, name: "Медведев З.С.", customer: null, registrationDate: new Date(2021, 9, 8), color: null },
    { id: 128, name: "Павлов Э.Ч.", customer: "НИИ Склифосовского", registrationDate: new Date(2023, 8, 8), color: "#EEC6E6" },
    { id: 129, name: "Петров Л.И.", customer: "ГКБ №1", registrationDate: new Date(2022, 3, 15), color: "#B7E4B6" },
    { id: 130, name: "Фомин Р.Р.", customer: "Поликлиника №3", registrationDate: new Date(2022, 5, 5), color: "#E2C9F5" },
    { id: 131, name: "Алексеев А.Н.", customer: "ГКБ №1", registrationDate: new Date(2018, 6, 29), color: "#DEB1BD" },
    { id: 132, name: "Суханов О.Ю.", customer: "Поликлиника №3", registrationDate: new Date(2022, 2, 4), color: "#B2EEE9" },
    { id: 133, name: "Громов К.А.", customer: null, registrationDate: new Date(2018, 4, 24), color: null },
    { id: 134, name: "Сидоров Я.Л.", customer: null, registrationDate: new Date(2025, 3, 28), color: "#C9FFBB" },
    { id: 135, name: "Виноградов Р.И.", customer: "ЦРБ Подольск", registrationDate: new Date(2024, 2, 16), color: "#C3C3DD" },
    { id: 136, name: "Николаев Я.Р.", customer: null, registrationDate: new Date(2022, 10, 14), color: "#FCE6DF" },
    { id: 137, name: "Блинов П.Т.", customer: "Поликлиника №3", registrationDate: new Date(2018, 11, 28), color: "#FDDAD9" },
    { id: 138, name: "Семёнов З.О.", customer: null, registrationDate: new Date(2021, 2, 23), color: null },
    { id: 139, name: "Марков Ф.Т.", customer: null, registrationDate: new Date(2019, 10, 11), color: "#FAE6B9" },
    { id: 140, name: "Петров М.Ю.", customer: "НИИ Склифосовского", registrationDate: new Date(2024, 8, 4), color: "#B2BEDD" },
    { id: 141, name: "Громов В.Е.", customer: "Поликлиника №3", registrationDate: new Date(2019, 4, 2), color: "#A3C2F9" },
    { id: 142, name: "Щербаков У.Н.", customer: "ГКБ №1", registrationDate: new Date(2024, 8, 11), color: "#E5FEEC" },
    { id: 143, name: "Волков А.Е.", customer: "МОНИКИ", registrationDate: new Date(2019, 0, 27), color: "#A6F6B7" },
    { id: 144, name: "Андреев Т.У.", customer: "НИИ Склифосовского", registrationDate: new Date(2025, 10, 7), color: "#F2FDEF" },
    { id: 145, name: "Морозов Ф.Ю.", customer: null, registrationDate: new Date(2018, 4, 4), color: "#E1ACE6" },
    { id: 146, name: "Морозов И.Ч.", customer: null, registrationDate: new Date(2025, 1, 26), color: null },
    { id: 147, name: "Лебедев В.О.", customer: "МОНИКИ", registrationDate: new Date(2022, 0, 23), color: "#F0BDAE" },
    { id: 148, name: "Николаев А.У.", customer: "ЦРБ Подольск", registrationDate: new Date(2021, 5, 19), color: "#D5F1FC" },
    { id: 149, name: "Фомин У.Э.", customer: "Поликлиника №3", registrationDate: new Date(2023, 3, 16), color: null },
    { id: 150, name: "Козлов К.М.", customer: null, registrationDate: new Date(2024, 10, 12), color: null },
];
